export const TOGGLE_THEME = "TOGGLE_THEME";
export const TOGGLE_SOUND = "TOGGLE_SOUND";
export const ADD_LABEL = "ADD_LABEL";
export const SAVE_TIMER_PREFERENCES = "SAVE_TIMER_PREFERENCES";
export const SAVE_ON_GOING_TIMER = "SAVE_ON_GOING_TIMER";
export const INCREMENT_TODAY_FOCUS_TIME = "INCREMENT_TODAY_FOCUS_TIME";
